spring.application.name=pedidos
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Natan123
spring.datasource.url=jdbc:postgresql://localhost:5433/TotemMc
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.public.key=classpath:keys/app.pub
jwt.private.key=classpath:keys/app.key